### ISSUE TITLE
Null value inconsistency

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql-exchange-graphcache#154]
**Request Query**

```
query RoomQuery($roomId: ID!) {
  room(id: $roomId) {
   id
   name
  }
}
```

**Server response**
```
{
   "data":{
      "room":null
   }
}
```

**Without graphcache**

1.  `{
   fetching:true,
   data:undefined
}`

2. `{
   fetching:false,
   data:{
      __typename:"Query",
      room:null
   }
}`

**With graphcache** and resolver of type `
 {
            Query: {
              room: (parent, args) => ({
                __typename: "Room",
                id: args.id
              })
            }
          }
`

1.  `{
   fetching:true,
   data:undefined
}`

2. `{
   fetching:false,
   data:null
}`

**Comment by kitten** [comment]
Hm so typically we don’t treat that as an inconsistency, but as a feature `undefined` is the initial data state in `urql` and it’s convenient as it indicates the absence of any possible data as a GraphQL API can never return `undefined`.

In Graphcache when we read from cache and no value is present however (be that because the resolver is missing data, the cache itself is missing data or because the server returned nothing) this yields `null` which is in fact a valid GraphQL value.

Now if we changed this I’d also like to change this on `urql` but the current reasoning is that it’d make it hard to differentiate between the initial state (cache empty) and `null` data

**Comment by zenios** [comment]
What ever the case, it has to stay consistent.

Imagine someone adding graphcache while he is in the middle of the development and suddenly finds out that null values should be handled differently :)

**Comment by kitten** [comment]
We may add an option to Graphcache then to force consistency, since it has distinct meanings, but that’s a good point 👍

**Comment by kitten** [comment]
I misread your issue. Specifically `data` is never `null` in Graphcache. https://github.com/FormidableLabs/urql-exchange-graphcache/blob/cd117690893fd162d31e8cdefd7f39f06254c66d/src/operations/query.ts#L103

You probably meant to open this issue on `urql`, since the hooks default to `undefined` for `data` there.

The other aspect here of data becoming `null` when your only queried field `room` is `null` is also expected behaviour. You should prepare your logic to handle `data` becoming `null` at all times, because that's the valid response for an empty query.

The reason why this field is missing and not `null` is because your custom resolver specifies an entity that doesn't exist. In such a case "playing it safe" and marking the field as missing is the safe behaviour. If you don't want that then you'll have to look into our schema awareness and pass Graphcache a schema. This will tell it that the `room` field may be `null`.
