### ISSUE TITLE
invalidateFragment

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql-exchange-graphcache#163]
Are there plans to add support for invalidateFragment?

**Comment by kitten** [comment]
Yes! We’ve been thinking of how this could make sense, but currently my opinion is that it may make more sense to invalidate an entity instead (either by passing a partial entity or an entity’s field like with `store.resolve`)

Would it be possible for you to explain your use-case here? It’d help us a lot in making a decision! 🙏

**Comment by zenios** [comment]
Sure i will simplify it a bit but i think it gets the point. So

Chat system

Room (RoomFragment) and users (UserFragment)

You have the option to multi chat inside a room and to private chat with a single user

User first joins the room 
1.Execute query to get room details
2.Subscribe to room updates (events are user joined / left)

On user join i add the UserFragment to cache using writeFragment
On user leave i would like to remove the Fragment from the cache

The reason i add the UserFragment to the cache is once i want to private chat with another user i 
execute another query to get users details but there is a great chance to have the user in the cache due to the previous writeFragment

Hope that was clear.

Have in mind that the system works even without removing the user from the cache but it will be nice to save some memory by removing not needed data

**Comment by kitten** [comment]
> Have in mind that the system works even without removing the user from the cache but it will be nice to save some memory by removing not needed data

You don't have to worry about saving memory, first of all. Graphcache has a built-in garbage collector that removes unreachable entities automatically as long as there are no circular references. :tada: Also, if you're only dealing with a single user instance you're adding/removing, it's likely that this isn't consuming that much memory.

> once i want to private chat with another user i
execute another query to get users details but there is a great chance to have the user in the cache due to the previous writeFragment

So if I understand this correctly, you're looking to share the `User` entity between the two queries. As long as your normalisation is set up correctly (which it is if you're not seeing any warnings in the console about `User`) it'll automatically share all `User` entities between queries.

You can then go a step further, if your `UsersDetails` query is likely to already be _completely_ in the cache, [you can write a small resolver](https://github.com/FormidableLabs/urql-exchange-graphcache/blob/master/docs/resolvers.md) that may allow Graphcache to get that `User` without actually sending that query to the server! This may look something like this:

```js
const cache = cacheExchange({
  resolvers: {
    Query: {
      user: (_parent, args) => ({ __typename: 'User', id: args.id })
    },
  },
});
```

(depending on your `Query` field to get the `UsersDetails`.

**Comment by zenios** [comment]
Invalidation was only needed just to save memory. since a built-in garbage collector is provided then everything is fine

Thanks
