### ISSUE TITLE
Implement a (new) mark & sweep GC

### ISSUE THREAD

**Issue by kitten** [FormidableLabs/urql-exchange-graphcache#44]
We want to add invalidation as a last resort to our normalised cache. It should be possible to do the following for instance:

```js
updates: {
  Mutation: {
    deleteAllPosts: (_, __, cache) => {
      // Example of invalidating the user, a single entity on Query
      cache.invalidate([cache.resolve('Query', 'me')]);
      // Example of invalidating all posts matching a pattern (in this case just a typename)
      cache.invalidate(cache.resolveAll('Post'));
    }
  }
}
```

In such a case it'd become vital to have the GC back in place. We had a simple GC, which was not sufficiently flexible to work with our newer `pessimism` store.

A new plan that is both efficient but needs a couple of changes is the following:

1. we make sure that our key separator is encoded in all keys, so `:` is always the separator
2. we create a mark & sweep GC that only deals with links (so we don't have to walk entities potentially?)
3. every entity that doesn't have a path of connecting links from `Query` will be deleted
4. to delete entities we match them by part of their key (hence the change in 1.)

This will also need a new iterable method on `pessimism`, possibly `toStream`

Edit: A consideration that'll be harder to think about are optimistic entries. How do we ensure that optimistic entries will not affect the GC? Do we differentiate between iterating over optimistic and non-optimistic values in `pessimism`? Do we iterate all of them and make each iteratee `[key, value, isOptimistic]`?

**Comment by JoviDeCroock** [comment]
I've tried starting a small implementation of this, some issues that I feel when thinking about this is that our links look like this at the moment: `Query.todos: []`, we have no way of knowing that we have to find the link to `todos`. For that matter we would need to be able to look for partial keys. Iterating over this would be a very expensive operation since in theory this would imply:

- Iterate over all links and find Query, we result in todos
- We take the array of todos and get Todo:1 and Todo:2 we add these to our visitedKeys
- Now we iterate over all links for both Todo:1 and Todo:2
- After the link walking we walk over all entityKeys to look at partial keys that don't match with our two visited Todo's and delete them
