### ISSUE TITLE
Crash on subsequent run of multiple 'concurrent' queries

### ISSUE THREAD

**Issue by jBugman** [FormidableLabs/urql-exchange-graphcache#69]
I have a page where two components run a query each, say `post(postID)` and `comments(postID)`.
On the fresh page load it works fine, but on navigation with react router (then there is some previous state) page crashes (on the second query) with
```
client.ts:205 Uncaught (in promise) TypeError: Cannot read property 'key' of undefined
    at Client.reexecuteOperation (client.ts:205)
    at exchange.ts:134
    at Set.forEach (<anonymous>)
    at processDependencies (exchange.ts:130)
    at updateCacheWithResult (exchange.ts:218)
    at wonka.es.js:920
    at wonka.es.js:377
    at wonka.es.js:377
    at wonka.es.js:1296
    at wonka.es.js:665
```
At first I thought it had something to do with list<->item relationship (post list and an individual post), but then I checked that it also happen on direct post->post transition.

**Comment by kitten** [comment]
I've got a tiny fix ready for this. I thought the condition that was being fixed was impossible, but it is indeed not. We've actually already encountered this issue in our default cache, but forgot to take this into account in Graphcache.

It's a really simple fix, but the problem is essentially that it's hard to reason about _why this case is indeed **not** impossible._ 😅
